### ISSUE TITLE
Unable to get version 3.0.0 working on Django 5.1.13

### ISSUE THREAD

**Issue by clausschive** [foo290/Django-Verify-Email#90]
Hi. I would love to use this nifty package, but I'm unable to get the new version working. The older version installs, but fails due to the Django 5.1.13 incompatibility. I've also tried installing 3.0.0 in a clean project with the same results. Any idea what's going on here?

```
Traceback (most recent call last):
  File "/Users/xxxxx/xxxxx/django-test/testapp/manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/testapp/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/django/apps/config.py", line 178, in create
    mod = import_module(mod_path)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/verify_email/__init__.py", line 1, in <module>
    from .email_handler import *
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/verify_email/email_handler.py", line 10, in <module>
    from .token_manager import TokenManager
  File "/xxxxxx/xxxxxx/xxxxxx/django-test/.venv/lib/python3.13/site-packages/verify_email/token_manager.py", line 28, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1305, in dataclass
    return wrap(cls)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 1008, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 860, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
                     f'{f.name} is not allowed: use default_factory')
ValueError: mutable default <class 'verify_email.app_configurations.GetFieldFromSettings'> for field settings is not allowed: use default_factory
```

**Comment by foo290** [comment]
thats dataclass error, what python version u using

**Comment by clausschive** [comment]
Wow! That was a super quick reply. I was on 3.12, but have now tried 3.13 with same results.

**Comment by foo290** [comment]
Ah, my bad, used data classes with mutable assignment, lemme fix that, gimme 10 mins, I'll update pypi with v3.0.1.

weird thing is, it didn't came on my machine even tho using same python version and several testcases
Anyways thanks for reporting ❤️

**Comment by clausschive** [comment]
Great! Can't wait to try this out :)

**Comment by foo290** [comment]
Yo, try now, Django-Verify-Email 3.0.2

**Comment by foo290** [comment]
Open the issue again if doesnt work

**Comment by clausschive** [comment]
Hey! I really appreciate your help. Unfortunately, the error persists with Django-Verify-Email==3.0.2.

```
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/dataclasses.py", line 860, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
                     f'{f.name} is not allowed: use default_factory')
ValueError: mutable default <class 'verify_email.token_manager.SafeURL'> for field safe_url_encoder is not allowed: use default_factory
```

**Comment by foo290** [comment]
Im aware 😢 its not happening in my sys so I have to hunt down every where I used dataclass to use default factory, fixing it!
sorry for the bugssssss!!!

**Comment by knownbug06** [comment]
how bout now @clausschive Django-Verify-Email 3.0.3

**Comment by clausschive** [comment]
It works until trying to import the send_verification_email function. I'm sorry to be such a pain...

`ImportError: cannot import name 'send_verification_email' from 'verify_email.email_handler' (/xxxxxx/xxxxxx/xxxxxx/vialog-django/.venv/lib/python3.13/site-packages/verify_email/email_handler.py)`

**Comment by knownbug06** [comment]
oh yea thats expected, those are breaking changes and those functions are removed, but the docs arent updated yet

use this:

```
from verify_email.email_handler import ActivationMailManager

response = ActivationMailManager.send_verification_link(self.user)

```

**Comment by knownbug06** [comment]
i need to update the docs, gonna use chatGPT for that lmao

**Comment by clausschive** [comment]
Yay! Things are looking up. I was able to send email by supplying request + form to send_verification_link. But when going to the verify url it didn't activate the saved user. Are there any other changes I need to take into consideration? Again, thanks for your great help :)

**Comment by knownbug06** [comment]
Any error? coz the test case to check user is activated or not is passing

```
    def test_process(self):
        user_token = TokenManager().generate_token_for_user(self.user)
        time.sleep(1)

        link = ActivationLinkManager.generate_link(user_token, self.user.email)
        full_url = f"http://testserver{link}"
        resp = self.client.get(full_url)
        self.assertEquals(resp.status_code, 200)
        self._refresh_user()
        self.assertTrue(self.user.is_active)

```

Testing started at 22:23 ...
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
Destroying test database for alias 'default'...
Process finished with exit code 0

**Comment by clausschive** [comment]
No errors. I just got redirected to login, but unable to log in. User appearing in db, so save works. I had to step out, so I’ll check more tomorrow. Again, big thanks 😀

**Comment by clausschive** [comment]
Hi! Just tested some more. Everything seems to work except for the verify_and_activate_user link to login which results in no reverse match, even though the 'accounts/login' route works when called manually. Any clue why this is?

```
[06/Nov/2024 11:13:09] "POST /accounts/create_user/ HTTP/1.1" 200 15
Reverse for '/accounts/login/' not found. '/accounts/login/' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/xxxxxx/xxxxxx/xxxxxx/xxxxxx/.venv/lib/python3.13/site-packages/verify_email/views.py", line 63, in verify_and_activate_user
    "link": reverse(login_page)
```

**Comment by knownbug06** [comment]
can u try setting LOGIN_URL = "your-login-view-name".

this is how django takes default login view to find reverse match. This has to be the name, not the url

**Comment by clausschive** [comment]
Hey. LOGIN_URL = "namespace:view" works like a charm. Thank you for your patience and great work. This is awesome :)

**Comment by knownbug06** [comment]
lol, the name is confusing, i need to be more clean on this one, again THANK YOU for reporting, it was a great find and kind of a sprint for me to fix stuff. I always appreciate people's efforts and suggestions in open source.

Thank you so much, take it easy ✌🏻 

closing it now!
